### ISSUE TITLE
getDailyWeather fails with error when result is empty

### ISSUE THREAD

**Issue by torsti** [rOpenGov/fmi#22]
As the title says. I assume the desired behaviour would be to return an empty object or something else. Or at least a more useful error message. The error seems to be in convertOGR. To which package does that belong?

```R
> client$getDailyWeather(startDateTime="2012-05-15", endDateTime="2012-07-17", fmisid = 100929)
trying URL 'http://data.fmi.fi/fmi-apikey/the-api-key/wfs?request=getFeature&storedquery_id=fmi::observations::weather::daily::timevaluepair&starttime=2012-05-15&endtime=2012-07-17&fmisid=100929&parameters=rrday,snow,tday,tmin,tmax'
Content type 'text/xml; charset=UTF-8' length 1988 bytes
==================================================
downloaded 1988 bytes

ogr2ogr -f GML  -splitlistfields /tmp/Rtmp9R6Bi7/file470e214c4ed /tmp/Rtmp9R6Bi7/file470e50047a05 PointTimeSeriesObservation
ERROR 1: Couldn't fetch requested layer 'PointTimeSeriesObservation'!
Error in convertOGR(sourceFile = private$cachedResponseFile, layer = layer,  : 
  Conversion failed.
```

I will try to investigate further.

**Comment by torsti** [comment]
`convertOGR` is defined in `rwfs/R/utils.R`, so not directly a problem for `fmi`.

**Comment by jlehtoma** [comment]
I think it would make sense to improve the error messaging. @torsti : would you like to open an issue at [rwfs](https://github.com/rOpenGov/rwfs)?

Note also that the upcoming 0.2.0 release still in the [develop](https://github.com/rOpenGov/rwfs/tree/develop) has quite a few things changed, most notably doing away with `ogr2ogr` by default.

**Comment by torsti** [comment]
Issue reported: [rwfs/issue/12](https://github.com/rOpenGov/rwfs/issues/12). Should we close here?

@jlehtoma Lazy me had missed the develop branch, thanks for pointing it out!

**Comment by jlehtoma** [comment]
@torsti no worries, lazy *me* haven't got around to finalize the 0.2.0 release to be merged to master. Thanks for opening up the issue, I'm closing this one.
