### ISSUE TITLE
Error "undefined columns selected"

### ISSUE THREAD

**Issue by lintusj1** [rOpenGov/fmi#26]
A fresh install to Ubuntu 16.04 gives

```
Error in `[.data.frame`(olddf, , measurementIndex[i]) : 
  undefined columns selected
```

when following the vignette for getting daily weather data with the function

```
client$getDailyWeather(...)
```

**Comment by lintusj1** [comment]
PR #25 fixes the above. It seems that the structure of the `layer` object has changed at some point.

**Comment by antagomir** [comment]
Thanks!
