### ISSUE TITLE
Check if rgdal supports streaming data directly from FMI

### ISSUE THREAD

**Issue by jlehtoma** [rOpenGov/fmi#9]
Previously this apparently was not possible, hence downloading the data and using `ogr2ogr` locally. Doing so seems to be very error prone, see if `rgdal` can do this using a newer version of `GDAL` (~~e.g. >= 2.1.0~~ 1.11, `rgdal` 2.0.0 is still in beta).

**Comment by jlehtoma** [comment]
This should be a priority for updating the package. I'm a bit swamped by work right now, so @torsti go ahead if you want to take a stab at this. Otherwise I'll be coming back to this in coming weeks.

**Comment by torsti** [comment]
@jlehtoma, let's see. This would be very useful for me too, but there are grant application deadlines in September, so I don't know yet when...

**Comment by jlehtoma** [comment]
Whatever time you can contribute @torsti !

**Comment by jlehtoma** [comment]
I'm moving this issue to `rwfs`, https://github.com/rOpenGov/rwfs/issues/4

**Comment by jlehtoma** [comment]
Update on the issue, it seems to be doable, see https://github.com/rOpenGov/rwfs/issues/4

ping @torsti
